account/urls.py
from django.urls import path
from account import views

app_name = 'account'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),

    path('password-reset/', views.UserPasswordResetView.as_view(), name='password-reset'),
    path('password-reset/done/', views.UserPasswordResetDoneView.as_view(), name='password-reset-done'),
    path('password-reset/confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),
         name='password-reset-confirm'),
    path('password-reset/complete/', views.UserPasswordResetCompleteView.as_view(), name='password-reset-complete'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('phone.urls')),
    path('', include('account.urls')),

    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

]

phone/urls.py
from django.urls import path
from phone import views

app_name = 'phone'
urlpatterns = [
    path('', views.indexView.as_view(), name='index-page'),
    path('create-phone/', views.CreatePhoneView.as_view(), name='create-phone'),
    path('update-phone/<int:id>', views.UpdatePhoneView.as_view(), name='update-phone'),
    path('delete-phone/<int:id>', views.DeletePhoneView.as_view(), name='delete-phone'),

    path('report/korean-brands/', views.KoreanBrandsAPIView.as_view(), name='report-korean-brands'),

    path('report/origin-brand-country/', views.PhoneOriginIsBrandCountryView.as_view(),
         name='report-origin-brand-country'),
    path('report/brand-phones/<str:title>/', views.BrandPhonesAPIView.as_view(), name='report-brand-phones'),
]

templates/includes/footer.html
<footer>
    Developed by Amir Jahangiri
</footer>

templates/includes/header.html
<header>
    <div>Dide pardaz</div>
    <nav>
        {% if request.user.is_authenticated %}
            <a href="{% url 'account:logout' %}">Logout</a>
            <a href="{% url 'phone:index-page' %}">Index Page</a>
        {% else %}
            <a href="{% url 'account:login' %}">Login</a>
            <a href="{% url 'account:register' %}">Register</a>

        {% endif %}
    </nav>
</header>

templates/includes/messages.html
{% if messages %}
        <ul class="errorlist">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

templates/includes/references.html
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        
        
        body {
            margin: 0;
        }

        footer {
            background-color: #333;
            color: white;
            text-align: center;
            padding: 20px;
            position: fixed;
            bottom: 0;
            width: 100%;
            font-family: Arial, sans-serif;
        }

        header {
            background-color: #333;
            color: white;
            padding: 15px 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            font-family: Arial, sans-serif;
        }

        header nav a {
            color: white;
            text-decoration: none;
            margin: 0 15px;
            font-size: 16px;
        }

        header nav a:hover {
            color: #ddd;
        }


        form {
            background-color: #444;
            padding: 20px 50px 20px 20px;
            border-radius: 8px;
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);
            width: 300px;
        }

        form p {
            margin: 10px 0;
        }

        label {
            display: block;
            margin-bottom: 5px;
            color: #ddd;
        }

        input[type="text"], input[type="password"], input[type="email"] {
            width: 100%;
            padding: 10px;
            border-radius: 4px;
            border: 1px solid #555;
            background-color: #333;
            color: white;
        }

        input[type="text"]:focus, input[type="password"]:focus, input[type="email"]:focus {
            border-color: #777;
            outline: none;
        }

        button {
            background-color: #555;
            color: white;
            padding: 10px;
            border: none;
            border-radius: 4px;
            width: 100%;
            cursor: pointer;
        }

        button:hover {
            background-color: #666;
        }

        .errorlist {
            background-color: #ffdddd; /* Light red background for visibility */
            border: 1px solid #ffaaaa; /* Slightly darker border */
            color: #d8000c; /* Dark red text color */
            padding: 10px; /* Padding around the text */
            border-radius: 4px; /* Rounded corners */
            margin: 10px 0; /* Margin for spacing */
            font-size: 14px; /* Slightly larger font size */
            list-style-type: none; /* Remove default list styling */
        }

        .errorlist li {
            margin: 5px 0; /* Space between list items */
        }
    </style>
    <title>{% block title %}

    {% endblock %}</title>